<?php
include("includes/var.php");
include("includes/config.php");
include("includes/function.php");
getpermbyusername($user);
include('includes/head.php');
include("includes/heading.php");
include('includes/base.php');
include('includes/foot.php');
?>