<?php
include("includes/var.php");
include("includes/config.php");
include("includes/function.php");
getpermbyusername($user);
include('includes/head.php');
include('includes/heading.php');
include('includes/users.php');
include('includes/foot.php');
?>